# In this file's directory, ~/.config/kitty:
# git clone --depth 1 https://github.com/dexpota/kitty-themes.git
# ln -s ./kitty-themes/themes/Tomorrow_Night.conf theme.conf
include theme.conf

enable_audio_bell no
cursor_shape block
shell_integration no-cursor
